CREATE TABLE IF NOT EXISTS sh_premium_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token_code VARCHAR(20) NOT NULL UNIQUE,
    status ENUM('ACTIVE', 'USED') DEFAULT 'ACTIVE',
    used_by VARCHAR(100) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
